<<<<<<< Updated upstream
# Generated by Django 5.2 on 2025-05-15 13:18
=======
# Generated by Django 5.2 on 2025-04-26 14:02
>>>>>>> Stashed changes

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('file_name', models.CharField(default='', max_length=250)),
                ('file', models.FileField(max_length=512, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> Stashed changes
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('name', models.CharField(max_length=100)),
=======
                ('name', models.CharField(max_length=128, unique=True)),
>>>>>>> Stashed changes
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.content')),
            ],
        ),
    ]
