# Generated by Django 5.2 on 2025-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="file_name",
            field=models.CharField(default="", max_length=250),
        ),
    ]
