# Generated by Django 5.2 on 2025-05-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="mentor",
            new_name="creator",
        ),
    ]
