# Generated by Django 5.2 on 2025-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_mentor_course_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="participants_count",
            field=models.IntegerField(default=0, verbose_name="Кол-во участников"),
            preserve_default=False,
        ),
    ]
