# Generated by Django 5.2 on 2025-05-13 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_participants_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                verbose_name="Продолжительность",
            ),
        ),
    ]
