# Generated by Django 5.2 on 2025-05-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_content_file_name"),
        ("courses", "0005_alter_lesson_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.content",
                verbose_name="Задание",
            ),
        ),
    ]
