# Generated by Django 5.2 on 2025-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_content_file_name"),
        ("courses", "0006_alter_lesson_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="assignment",
        ),
        migrations.AddField(
            model_name="lesson",
            name="assignments",
            field=models.ManyToManyField(
                blank=True,
                related_name="lessons",
                to="common.content",
                verbose_name="Материалы",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_date",
            field=models.DateTimeField(verbose_name="Дата проведения"),
        ),
    ]
