# Generated by Django 5.2 on 2025-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_lessonstatistics_lesson_lesson_statics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="zoom_id",
            field=models.URLField(max_length=512, unique=True, verbose_name="Zoom ID"),
        ),
    ]
