# Generated by Django 5.2 on 2025-05-27 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_conference_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference",
                to="courses.lesson",
                verbose_name="Занятие",
            ),
        ),
    ]
